[package]
name = "tie-llvm"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "tie 语言编译器（四段式：tie-prep 预处理 + 自研前端 + LLVM 中后端）：源码 → 预处理 → LLVM IR → opt 优化 → clang/lld 链接"

[dependencies]
tie-prep = { path = "../tie-prep" }
tie-frontend = { path = "../tie-frontend" }

[lints]
workspace = true
